version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: optin_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # Scripts de inicialização
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "SELECT 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  api:
    build: .
    container_name: optin_api
    environment:
      DB_HOST: optin_sqlserver
      DB_NAME: optin_manager
      DB_USER: sa
      DB_PASSWORD: "YourStrong!Passw0rd"
      DB_DRIVER: "ODBC Driver 18 for SQL Server"
    depends_on:
      db:
        condition: service_healthy  # Espera o SQL Server estar pronto
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

volumes:
  sqlserver_data: